services:
    _defaults: { autowire: true, autoconfigure: true, public: true }

    # Contao frontend module Markocupic\RszJahresprogrammBundle\Controller\FrontendModule\RszJahresprogrammListModuleController
    Markocupic\RszJahresprogrammBundle\Controller\FrontendModule\RszJahresprogrammListModuleController:
      tags:
      - { name: contao.frontend_module, category: rsz_frontend_modules, template: mod_rsz_jahresprogramm_list, type: rsz_jahresprogramm_list_module }
      - { name: container.service_subscriber }
      public: true

    # Contao frontend module Markocupic\RszJahresprogrammBundle\Controller\FrontendModule\RszJahresprogrammReaderModuleController
    Markocupic\RszJahresprogrammBundle\Controller\FrontendModule\RszJahresprogrammReaderModuleController:
      tags:
      - { name: contao.frontend_module, category: rsz_frontend_modules, template: mod_rsz_jahresprogramm_reader, type: rsz_jahresprogramm_reader_module }
      - { name: container.service_subscriber }
      public: true
